import type { Metadata } from "next";
import { Jost, Jockey_One } from '@next/font/google'

import "./tailwind.scss";
import "./globals.scss";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { Providers } from "./providers";
import MouseCursor from "@/components/Personal/MouseCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
})

const jockey_One = Jockey_One({ 
  subsets: ["latin"],
  weight: "400",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light">
      <body className={`${jost.className} ${jockey_One.className}`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <MouseCursor />
      </body>
    </html>
  );
}
