import type { Metadata } from "next";
import { Anonymous_Pro } from '@next/font/google'

import "./tailwind.scss";
import "./globals.scss";

import MouseCursor from "@/components/Default/MouseCursor";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const anonymous_pro = Anonymous_Pro({
  subsets: ["latin"],
  weight: ["400", "700"],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light">
      <body className={`${anonymous_pro.className}`}>
        <Header />
        {children}
        <MouseCursor />
      </body>
    </html>
  );
}
